<?php

/**
 * @file
 * Backdrop integration with Animate.css, bunch of cool, fun, and cross-browser animations for you to use in your projects.
 */

/**
 * Implements hook_config_info().
 */
function animate_css_config_info() {
  $prefixes['animate_css.settings'] = array(
    'label' => t('animate_css settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_libraries_info().
 */
function animate_css_libraries_info() {
  $libraries['animate'] = array(
    'name' => 'animate',
    'vendor url' => 'http://daneden.me/animate/',
    'download url' => 'https://github.com/daneden/animate.css/archive/master.zip',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/((?:\d+\.?){2,3})/',
    ),
    'files' => array(
      'css' => array(
        'animate.css',
      ),
    ),
  );

  return $libraries;
}

 /**
 * Implements hook_page_menu().
 */
function animate_css_menu() {
  $items = array();

  $items['admin/config/user-interface/animate_css'] = array(
    'title' => 'Administer Animate CSS settings',
    'description' => 'Administer Animate CSS settings',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('animate_css_settings'),
    'access arguments' => array('access animate_css settings'),
    'file' => 'animate_css.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_init().
 */
function animate_css_init() {
  $animate_css_visibility = config_get('animate_css.settings', 'animate_css_visibility');
  // Compare with the internal and path alias (if any).
  $path = backdrop_get_path_alias($_GET['q']);
  $animate_css_pages = config_get('animate_css.settings', 'animate_css_pages');

  // if $animate_css_visibility is 0, then except these pages.  if $animate_css_visibility is 1, then only these pages.
  if ($animate_css_visibility > 0)
  {
    $page_match = backdrop_match_path($path, $animate_css_pages);
  }
  else {
    $page_match = !backdrop_match_path($path, $animate_css_pages);
  }

   if ($page_match > 0)
  {
  // If we have a page match according to the admin settings, load up the Animate CSS file.
  backdrop_load('module', 'libraries');
  libraries_load('animate');
  }

}
